### ISSUE TITLE
Politica de privacidade 10/03

### ISSUE THREAD

**Issue by Nirayuki** [Nirayuki/deshah#19]
[Política de Privacidade.docx](https://github.com/Nirayuki/deshah/files/6119619/Politica.de.Privacidade.docx)

Política de Privacidade
Na (DESHAH GAME), privacidade e segurança são prioridades e nos comprometemos com a transparência do tratamento de dados pessoais dos nossos usuários/clientes. Por isso, esta presente Política de Privacidade estabelece como é feita a coleta, uso e transferência de informações de clientes ou outras pessoas que acessam ou usam nosso site.

Ao utilizar nossos serviços, você entende que coletaremos e usaremos suas informações pessoais nas formas descritas nesta Política, sob as normas de Proteção de Dados (LGPD, Lei Federal 13.709/2018), das disposições consumeristas da Lei Federal 8078/1990 e as demais normas do ordenamento jurídico brasileiro aplicáveis.

Dessa forma, a (DESHAH GAME), doravante denominada simplesmente como “(DESHAH)”, inscrita no CNPJ/MF sob o nº (nº do CNPJ), no papel de Controladora de Dados, obriga-se ao disposto na presente Política de Privacidade.

Medidas de segurança

O Jogos Offline tomará todas as medidas razoavelmente necessárias para garantir que seus dados sejam tratados com segurança e de acordo com esta Política de Privacidade e nenhuma transferência de seus Dados Pessoais será realizada para uma organização ou país, a menos que haja controles adequados, incluindo a segurança de seus dados e outras informações pessoais.

Consentimento

É a partir do seu consentimento que tratamos os seus dados pessoais. O consentimento é a manifestação livre, informada e inequívoca pela qual você autoriza a (DESHAH GAME) a tratar seus dados.

Assim, em consonância com a Lei Geral de Proteção de Dados, seus dados só serão coletados, tratados e armazenados mediante prévio e expresso consentimento.

O seu consentimento será obtido de forma específica para cada finalidade acima descrita, evidenciando o compromisso de transparência e boa-fé da (DESHAH GAME) para com seus usuários/clientes, seguindo as regulações legislativas pertinentes.

Ao utilizar os serviços da (DESHAH GAME) e fornecer seus dados pessoais, você está ciente e consentindo com as disposições desta Política de Privacidade, além de conhecer seus direitos e como exercê-los.

A qualquer tempo e sem nenhum custo, você poderá revogar seu consentimento.

É importante destacar que a revogação do consentimento para o tratamento dos dados pode implicar a impossibilidade da performance adequada de alguma funcionalidade do site que dependa da operação. Tais consequências serão informadas previamente.

Quais são os seus direitos?

A (DESHAH GAME) assegura a seus usuários/clientes seus direitos de titular previstos no artigo 18 da Lei Geral de Proteção de Dados. Dessa forma, você pode, de maneira gratuita e a qualquer tempo:

Confirmar a existência de tratamento de dados, de maneira simplificada ou em formato claro e completo.
Acessar seus dados, podendo solicitá-los em uma cópia legível sob forma impressa ou por meio eletrônico, seguro e idôneo.
Corrigir seus dados, ao solicitar a edição, correção ou atualização destes.
Limitar seus dados quando desnecessários, excessivos ou tratados em desconformidade com a legislação através da anonimização, bloqueio ou eliminação.
Solicitar a portabilidade de seus dados, através de um relatório de dados cadastrais que a (DESHAH) trata a seu respeito.
Eliminar seus dados tratados a partir de seu consentimento, exceto nos casos previstos em lei.
Revogar seu consentimento, desautorizando o tratamento de seus dados.
Informar-se sobre a possibilidade de não fornecer seu consentimento e sobre as consequências da negativa.

Requerimentos legais

Jogos Offline e podem divulgar seus dados pessoais na crença de boa fé que tal ação é necessária para:

Para cumprir uma obrigação legal

Para proteger e defender os direitos ou propriedade de Jogos Offline e Mobile Gamer
Para proteger e defender os direitos ou propriedade de Jogos Offline…
Para proteger a segurança pessoal dos usuários do Serviço ou do público
Para proteger contra responsabilidade legal

Segurança de dados

A segurança dos seus dados é importante para nós, mas lembre-se de que nenhum método de transmissão pela Internet ou método de armazenamento eletrônico é 100% seguro. Embora nos esforcemos para usar meios comercialmente aceitáveis para proteger seus dados pessoais, não podemos garantir sua segurança absoluta.

**Comment by eaassuncao** [comment]
[Política de Privacidade.docx](https://github.com/Nirayuki/deshah/files/6119617/Politica.de.Privacidade.docx)
