### ISSUE TITLE
Diagrama de Classes 04/04

### ISSUE THREAD

**Issue by eaassuncao** [Nirayuki/deshah#34]
Elaborar o Diagrama de Classes para o Site.

Deve ser feito um diagrama para o usuário quando estiver logado no site e outro diagrama quando não estiver logado, pois os dois tem ferramentas diferentes.

**Comment by Nirayuki** [comment]
https://drive.google.com/file/d/1xrynmiXCarcWhoIRx-3YtCfoIL-uTd3u/view?usp=sharing
